
[filters.8]
phase_error_history_length = 10
sma_window = 15
volume_scaling = 1.0
batch_size = 2000
ring_decay = 0.994
enable_clamping = false
phase_detector_gain = 0.15
loop_bandwidth = 0.02
max_frequency_deviation = 0.3
q_factor = 2.0
clamping_threshold = 1.0e-6
lock_threshold = 0.6

[filters.1]
phase_error_history_length = 10
sma_window = 15
volume_scaling = 1.0
batch_size = 2000
ring_decay = 0.994
enable_clamping = false
phase_detector_gain = 0.15
loop_bandwidth = 0.02
max_frequency_deviation = 0.3
q_factor = 1.6
clamping_threshold = 1.0e-6
lock_threshold = 0.6

[filters.21]
phase_error_history_length = 10
sma_window = 15
volume_scaling = 1.0
batch_size = 2000
ring_decay = 0.994
enable_clamping = false
phase_detector_gain = 0.15
loop_bandwidth = 0.02
max_frequency_deviation = 0.3
q_factor = 2.2
clamping_threshold = 1.0e-6
lock_threshold = 0.6

[filters.5]
phase_error_history_length = 10
sma_window = 15
volume_scaling = 1.0
batch_size = 2000
ring_decay = 0.994
enable_clamping = false
phase_detector_gain = 0.15
loop_bandwidth = 0.02
max_frequency_deviation = 0.3
q_factor = 1.9
clamping_threshold = 1.0e-6
lock_threshold = 0.6

[filters.2]
phase_error_history_length = 10
sma_window = 15
volume_scaling = 1.0
batch_size = 2000
ring_decay = 0.994
enable_clamping = false
phase_detector_gain = 0.15
loop_bandwidth = 0.02
max_frequency_deviation = 0.3
q_factor = 1.7
clamping_threshold = 1.0e-6
lock_threshold = 0.6

[filters.13]
phase_error_history_length = 10
sma_window = 15
volume_scaling = 1.0
batch_size = 2000
ring_decay = 0.994
enable_clamping = false
phase_detector_gain = 0.15
loop_bandwidth = 0.02
max_frequency_deviation = 0.3
q_factor = 2.1
clamping_threshold = 1.0e-6
lock_threshold = 0.6

[filters.3]
phase_error_history_length = 10
sma_window = 15
volume_scaling = 1.0
batch_size = 2000
ring_decay = 0.994
enable_clamping = false
phase_detector_gain = 0.15
loop_bandwidth = 0.02
max_frequency_deviation = 0.3
q_factor = 1.8
clamping_threshold = 1.0e-6
lock_threshold = 0.6
[io]
save_intermediate = false
input_file = "data/YM_06-25_bars_market_time.jld2"
error_on_missing_file = true
compress_output = true
log_progress = true
output_file = "data/YM_06-25_fibonacci_filtered.jld2"
parallel_processing = false
validate_inputs = true
backup_on_overwrite = false
max_memory_gb = 12.0
progress_interval = 1000

[metadata]
name = "fast"
active_periods = [1, 2, 3, 5, 8, 13, 21]
config_type = "standard"
created = "2025-08-13T17:44:25.375"
description = "Fast processing with fewer periods"
version = "3.0"
max_filters = 20

[pll]
enabled = false

[processing]
include_price_levels = true
include_volatility = true
include_diagnostics = true
include_momentum = true
