
[filters.8]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8

[filters.1]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8

[filters.21]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8

[filters.5]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8

[filters.2]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8

[filters.34]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8

[filters.13]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8

[filters.3]
phase_error_history_length = 30
sma_window = 20
volume_scaling = 1.0
batch_size = 1000
ring_decay = 0.997
enable_clamping = true
phase_detector_gain = 0.05
loop_bandwidth = 0.005
max_frequency_deviation = 0.1
q_factor = 4.0
clamping_threshold = 1.0e-7
lock_threshold = 0.8
[io]
save_intermediate = false
input_file = "data/YM_06-25_bars_market_time.jld2"
error_on_missing_file = true
compress_output = true
log_progress = true
output_file = "data/YM_06-25_fibonacci_filtered.jld2"
parallel_processing = false
validate_inputs = true
backup_on_overwrite = false
max_memory_gb = 12.0
progress_interval = 1000

[metadata]
name = "high_q"
active_periods = [1, 2, 3, 5, 8, 13, 21, 34]
config_type = "standard"
created = "2025-08-13T17:44:25.377"
description = "High Q factor for sharp frequency response"
version = "3.0"
max_filters = 20

[pll]
enabled = false

[processing]
include_price_levels = true
include_volatility = true
include_diagnostics = true
include_momentum = true
